class WebLogType:
    AI_SEARCH_SERVICE_TO_MAIN_KIDOK_SERVICE: str = "AI_SEARCH_SERVICE_TO_MAIN_KIDOK_SERVICE"
    AI_SEARCH_RESULT_SOURCES_TO_MAIN_KIDOK_SERVICE: str = "AI_SEARCH_RESULT_SOURCES_TO_MAIN_KIDOK_SERVICE"
